# Generated by Django 3.1.7 on 2021-04-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mark_as_read',
            field=models.BooleanField(default=False),
        ),
    ]
