# Generated by Django 3.1.7 on 2021-04-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210411_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='config',
            name='favicon',
            field=models.ImageField(upload_to='config'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to='profile'),
        ),
    ]
